server:
  port: 8083
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myqq?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
    username: root
    password: root

##    hikari:
##      idle-timeout: 60000
##      maximum-pool-size: 30 #最大连接数
##   邮件服务默认注释
#  mail:
#    host: smtp.qq.com #邮件服务器
#    username:
#    password:
#    protocol: smtp
#    default-encoding: UTF-8
#    test-connection: true
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#            required: true
mybatis:
  type-aliases-package: com.oicq.Entity
  mapper-locations: classpath:/mybatis/*.xml